# Generated by Django 5.1.2 on 2024-10-09 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
