# Generated by Django 5.1.2 on 2024-10-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
